# Generated by Django 3.1.2 on 2020-11-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivo', '0002_auto_20201101_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
